### ISSUE TITLE
An error has occurred, please try to create your incident again

### ISSUE THREAD

**Issue by MesiChaka** [OfficeDev/microsoft-teams-emergency-operations-center#281] opened 2024-10-25 17:05 UTC
When we create the incident with Role assignment , it doesn't create the incident. It will give an error that   "An error has occurred, please try to create your incident again"

**Comment by v-ajaysahu** [comment] 2024-10-28 09:59
@MesiChaka , thanks for bringing this to our attention.
Could you please open Teams in your browser, open developer tools in your browser, and launch the TEOC app? Once there, attempt to replicate the issue and share both the console logs and network traces with us. This will help us to troubleshooting efforts.

**Comment by v-ajaysahu** [comment] 2024-11-20 14:14
We are closing this issue as it is a duplicate of issue #240.

**Closed by v-ajaysahu** 2024-11-20 14:14 UTC
Labels: Needs: Attention :wave:
