### ISSUE TITLE
EOC deployment error

### ISSUE THREAD

**Issue by almaucla** [OfficeDev/microsoft-teams-emergency-operations-center#37] opened 2022-08-09 17:48 UTC
Hello,

I'm getting the below error when I try to deploy the app

status": "Failed",
    "error": {
        "code": "InvalidTemplateDeployment",
        "message": "The template deployment 'simpleAuthProvision' is not valid according to the validation procedure. The tracking id is 'd09969eb-49ae-41d7-b2b5-6323d9694473'. See inner errors for details.",
        "details": [
            {
                "message": "Object reference not set to an instance of an object."
            }

**Comment by v-prigunasek** [comment] 2022-08-10 05:20
Hi @almaucla,

Thanks for reporting the issue. 
Could you please provide us the screenshots of the Deployments (Click on Deployments in the Resource Group that you have created) and the simpleAuthProvision screen? That would be great for us to understand the issue and to further assist you on resolving this issue.

Thanks!

**Comment by v-prigunasek** [comment] 2022-08-11 15:24
Hi @almaucla.

Thanks for updating us on the status. Good to hear the issue is resolved. Please feel free to reach out to us if you face any issues.

**Closed by v-prigunasek** 2022-08-11 15:24 UTC
Labels: question, Needs: author feedback
