### ISSUE TITLE
TEOC Issues 

### ISSUE THREAD

**Issue by Chris-USDA** [OfficeDev/microsoft-teams-emergency-operations-center#240] opened 2024-08-29 15:19 UTC
Issue 1: Add new incident button has disappeared; the new button has been removed for every TEOC user. Permissions have not changed but the button is gone. It was there last week. 
Issue 2: Information inputted into a new incident disappears after saving it. The information shows in history but not in the case and we cannot do anything with it since the data is showing as blank. 
Issue 3: Can not add TEOC to a group the SAVE button is grayed out. It was there last week. App administration shows no changes since implementing TEOC. 
Issue 4: Can the Location field pull from another source besides BING?
Issue 5: Blank spaces in fields making it hard to scroll for next option.

**Comment by v-saikirang** [comment] 2024-08-30 11:17
Hi @Chris-USDA,

Thanks for reaching out to us.

Issue 1: Add new incident button has disappeared; the new button has been removed for every TEOC user. Permissions have not changed but the button is gone. It was there last week.
          TEOC Team: Have you enabled Roles under Config Settings:

![image](https://github.com/user-attachments/assets/c2540c9e-50c8-47c2-889b-8b23ccb4223f)

Issue 2: Information inputted into a new incident disappears after saving it. The information shows in history but not in the case and we cannot do anything with it since the data is showing as blank.
       TEOC Team: Can you please share screenshot of what you are referring to.
Issue 3: Can not add TEOC to a group the SAVE button is grayed out. It was there last week. App administration shows no changes since implementing TEOC.
        TEOC Team: Can you please share screenshot of what you are referring to.
Issue 4: Can the Location field pull from another source besides BING?
        TEOC Team: No
Issue 5: Blank spaces in fields making it hard to scroll for next option.
         TEOC Team: We have already fixed this and the update will be available shortly in 1-2 weeks.

And have there been any changes recently. Did you upgrade recently. Which version are you on.  

Thanks.

**Comment by sivanikakuru09** [comment] 2024-08-30 14:47
Where is the enable setting for this role?

**Comment by Chris-USDA** [comment] 2024-08-30 17:29
Issue 2: Information inputted into a new incident disappears after saving it. The information shows in history but not in the case and we cannot do anything with it since the data is showing as blank.
TEOC Team: Can you please share screenshot of what you are referring to.

After we create an incident and all the required information and then go back into the incident to update the incident all the previously entered information is gone. The incident cannot be update without re-entering all the previous data again. 
Trying to figure out why all of the information in the incident disappears from the incident form but shows in the incident history. This does not happen all of the time but most of the time.  
![TEOC Incident History](https://github.com/user-attachments/assets/3863d0a8-fd69-4d3f-ad5e-959d6bb48e46)
![TEOC Incident Form](https://github.com/user-attachments/assets/a7e96965-1404-4bcd-ac0a-ecff60b79152)

**Comment by v-ajaysahu** [comment] 2024-09-02 10:10
@Chris-USDA ,
Thank you for providing the screenshot. To further assist in troubleshooting the issue, could you please provide the console logs and network traces? Launch Teams in your browser, access the developer tools, and open the TEOC app. Try to reproduce the issue and then share the console logs and network traces with us.

**Comment by Chris-USDA** [comment] 2024-09-03 20:20
Thank you, will be sending you the information as soon as we can.

Thank you.

Chris A. Smith
Innovation Coordinator (Contractor - Focused Management, Inc.)
Infrastructure Operations Division
Office of the Chief Information Officer Client Experience Center
Phone: 314-457-4874
CEC Customer Site <https://usdagcc.sharepoint.com/>

**Comment by Chris-USDA** [comment] 2024-09-04 14:15
Either we are able to create an incident in TEOC and it does not retain the data or we can't create an incident because of the following error: **An error has occurred, please try to create your incident again.** 

![image](https://github.com/user-attachments/assets/bb5958c4-29cf-43b7-8cdf-341848de3f4e)

**Comment by Chris-USDA** [comment] 2024-09-05 15:28
We have figured out the issue appears to be when we Role Assignments. 
Can we figure out why this is occurring? This is a main part of the Tool that we need.

**Comment by v-ajaysahu** [comment] 2024-09-09 13:39
@Chris-USDA ,
As previously requested, could you please share the logs? Also please share your email address and your availability so that we can schedule a Microsoft Teams Meeting so that we can troubleshoot the issue.
Please note: We are available from 10:00 AM to 7:30 PM IST only.

**Comment by Chris-USDA** [comment] 2024-09-10 14:00
Sivani,

Are you able to provide the logs?
We are still not able to create incidents consistently that retain data.

Thank you.

Chris A. Smith
Innovation Coordinator (Contractor - Focused Management, Inc.)
Infrastructure Operations Division
Office of the Chief Information Officer Client Experience Center
Phone: 314-457-4874
CEC Customer Site <https://usdagcc.sharepoint.com/>

**Comment by v-ajaysahu** [comment] 2024-10-28 11:19
@Chris-USDA ,
Please share the logs here. I'm reopening this issue.

**Comment by v-ajaysahu** [comment] 2024-11-27 08:03
@Chris-USDA ,
Following the deployment of the hotfix released last week, you have confirmed that the issues have been resolved, and you can proceed. 
The issues you encountered were due to multiple commas in the display name and the Graph API for tab creation hitting the threshold limit. To address these, we updated our code to handle multiple commas in the display name and added an error handler for Graph API tab creation, which will pause for 1 second before retrying, with a maximum of 3 retries. As your issues are now resolved, we are closing this case. 
If you have any further issues or questions, please feel free to post them here.

**Closed by v-ajaysahu** 2024-11-27 08:03 UTC
Labels: Needs: Attention :wave:
