### ISSUE TITLE
Failing to Create Incident

### ISSUE THREAD

**Issue by C0LDW1R3D** [OfficeDev/microsoft-teams-emergency-operations-center#292] opened 2024-11-18 21:25 UTC
I just staged the TEOC Site, app and all, after several deletes and re-deployments, I have it somewhat functional.

2 issues I am facing.

The first main one, is that when I create an incident, it fails, I can see that, briefly I can see that the Azure Group is made and the members are a part of the group, so I don't think its group creation, it may be teams' creation? I'm unsure, what's the best way to troubleshoot this error?

Secondly, I can access it on the computer (Windows - via teams) but it's won't work on my mobile, it's stuck at the log in screen and does a loop of logging into the app, on windows however its auto logged in, and displaying my name (doesn't matter if I am on or off the corporate network, Cellular or Wi-Fi) thoughts? 

Cheers

**Comment by v-saikirang** [comment] 2024-11-19 15:26
Hi @C0LDW1R3D,

Thanks for reaching out to us. Please allow us some time. We will get back to you ASAP.
Thanks.

**Comment by C0LDW1R3D** [comment] 2024-11-19 21:17
@v-saikirang,

I will await your response, cheers.

**Comment by v-ajaysahu** [comment] 2024-11-20 06:10
@C0LDW1R3D ,
Could you kindly provide the network logs? Please open Microsoft Teams in your browser and access the developer tools. Then, open the TEOC app in Teams and attempt to reproduce the issue. Finally, export the network traces from the network tab in the developer tools.

**Comment by C0LDW1R3D** [comment] 2024-11-21 04:19
[teams.microsoft.com (3).zip](https://github.com/user-attachments/files/17839730/teams.microsoft.com.3.zip)

**Comment by v-ajaysahu** [comment] 2024-11-21 12:54
@C0LDW1R3D ,
Thank you for providing the logs. We will need some time to review them thoroughly.

**Comment by v-ajaysahu** [comment] 2024-11-22 10:00
Please update to the latest hot fix released today and verify if the issue still exists. If the issue persists, kindly provide the following details:

1. Share the App registration permission screenshot as outlined in step 5 [Deployment Guide · OfficeDev/microsoft-teams-emergency-operations-center Wiki](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#5-add-permissions-to-microsoft-graph-azure-ad-app).
2. Provide the screenshot of the added Client application GUID in the scope as detailed in step 4 ix [Deployment Guide · OfficeDev/microsoft-teams-emergency-operations-center Wiki](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#4-set-up-authentication).
3. Additionally, confirm if there is a specific pattern for the failure of Incident creation or if it consistently fails.

**Comment by C0LDW1R3D** [comment] 2024-11-24 22:54
1. ![image](https://github.com/user-attachments/assets/f4fbccee-1ebe-4377-9b31-95e13f61658d)
2. ![image](https://github.com/user-attachments/assets/5a50c113-2db3-4a6c-ada4-9fa1afab2a06)
3. Its always the same step.
4. 
![image](https://github.com/user-attachments/assets/a547b43a-267a-446e-8f22-d474ec39a92c)

the sharepoint app was blocked, ive allowed it, still no difference, this app in teams has the ID of 2a527703-1f6f-4559-a332-d8a7d288cd88, which is also the same one showing up in the console logs provided earlier. i added the sharepoint app to my global default permission policies, could it be something down this line?

**Comment by C0LDW1R3D** [comment] 2024-11-25 21:36
I've fixed it.
it was due to app permission policy. i allowed the sharepoint app, to my TEOC app permission policy, and tested it, everything worked fine and was created.

Thanks for checking out anyway, but you can close this now, ill be deleting my console logs and network logs.

**Comment by v-ajaysahu** [comment] 2024-11-26 08:52
@C0LDW1R3D ,
Thank you for confirming that your issue is resolved. 
The problem was due to the SharePoint App permission policy, which has now been enabled, that resolved the issue. Therefore, we are closing this case. If you encounter any other issues or have questions, please feel free to ask here.

**Closed by v-ajaysahu** 2024-11-26 08:52 UTC
Labels: Needs: Attention :wave:
