### ISSUE TITLE
TEOC install complete but can't sign in

### ISSUE THREAD

**Issue by rvwilk** [OfficeDev/microsoft-teams-emergency-operations-center#169] opened 2024-02-16 00:10 UTC
After creating the teams app I click on the Login button Under the Welcome heading. A box popped up to grant permission on behalf of the organization. Which I did, now when I click login, a box appears for second then it disappears I am unable to sign in. What am I missing?

**Comment by v-asshrirao** [comment] 2024-02-16 09:25
@rvwilk, Thank you for reporting this. 
Can you please share console logs and network trace which will help us troubleshoot the issue.
Also request you to share the manifest files with us.

**Comment by rvwilk** [comment] 2024-02-16 16:47
Here are the manifest logs:

{
	"id": "fbf4be06-3262-41c8-8383-3cfe59ce6665",
	"acceptMappedClaims": null,
	"accessTokenAcceptedVersion": null,
	"addIns": [],
	"allowPublicClient": null,
	"appId": "08627c1d-e92e-4ab7-a41f-12c7dd5d0ff5",
	"appRoles": [],
	"oauth2AllowUrlPathMatching": false,
	"createdDateTime": "2024-02-15T22:16:32Z",
	"description": null,
	"certification": null,
	"disabledByMicrosoftStatus": null,
	"groupMembershipClaims": null,
	"identifierUris": [
		"api://brighameoc.azurewebsites.net/08627c1d-e92e-4ab7-a41f-12c7dd5d0ff5"
	],
	"informationalUrls": {
		"termsOfService": null,
		"support": null,
		"privacy": null,
		"marketing": null
	},
	"keyCredentials": [],
	"knownClientApplications": [],
	"logoUrl": null,
	"logoutUrl": null,
	"name": "teoc",
	"notes": null,
	"oauth2AllowIdTokenImplicitFlow": false,
	"oauth2AllowImplicitFlow": false,
	"oauth2Permissions": [
		{
			"adminConsentDescription": "Allows Teams to call the app’s web APIs as the current user",
			"adminConsentDisplayName": "Teams can access app's web API",
			"id": "4c099a9b-6f5b-4b12-ab1e-b9d7e98110bc",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"type": "User",
			"userConsentDescription": null,
			"userConsentDisplayName": null,
			"value": "access_as_user"
		}
	],
	"oauth2RequirePostResponse": false,
	"optionalClaims": {
		"idToken": [],
		"accessToken": [
			{
				"name": "idtyp",
				"source": null,
				"essential": false,
				"additionalProperties": []
			}
		],
		"saml2Token": []
	},
	"orgRestrictions": [],
	"parentalControlSettings": {
		"countriesBlockedForMinors": [],
		"legalAgeGroupRule": "Allow"
	},
	"passwordCredentials": [
		{
			"customKeyIdentifier": null,
			"endDate": "2026-02-15T07:00:00Z",
			"keyId": "83b85eb1-47ce-45c9-a01c-0aac566bc03e",
			"startDate": "2024-02-15T22:18:42.812Z",
			"value": null,
			"createdOn": "2024-02-15T22:19:59.4860749Z",
			"hint": "ZE~",
			"displayName": "teoc secret"
		}
	],
	"preAuthorizedApplications": [
		{
			"appId": "4345a7b9-9a63-4910-a426-35363201d503",
			"permissionIds": [
				"4c099a9b-6f5b-4b12-ab1e-b9d7e98110bc"
			]
		},
		{
			"appId": "00000002-0000-0ff1-ce00-000000000000",
			"permissionIds": [
				"4c099a9b-6f5b-4b12-ab1e-b9d7e98110bc"
			]
		},
		{
			"appId": "d3590ed6-52b3-4102-aeff-aad2292ab01c",
			"permissionIds": [
				"4c099a9b-6f5b-4b12-ab1e-b9d7e98110bc"
			]
		},
		{
			"appId": "4765445b-32c6-49b0-83e6-1d93765276ca",
			"permissionIds": [
				"4c099a9b-6f5b-4b12-ab1e-b9d7e98110bc"
			]
		},
		{
			"appId": "1fec8e78-bce4-4aaf-ab1b-5451cc387264",
			"permissionIds": [
				"4c099a9b-6f5b-4b12-ab1e-b9d7e98110bc"
			]
		},
		{
			"appId": "5e3ce6c0-2b1f-4285-8d4b-75ee78787346",
			"permissionIds": [
				"4c099a9b-6f5b-4b12-ab1e-b9d7e98110bc"
			]
		}
	],
	"publisherDomain": "bcutah.onmicrosoft.com",
	"replyUrlsWithType": [
		{
			"url": "https://brighameoc.azurewebsites.net.azurewebsites.net/blank-auth-end.html",
			"type": "Spa"
		},
		{
			"url": "https://brighameoc.azurewebsites.net/auth-end.html",
			"type": "Web"
		},
		{
			"url": "https://brighameoc.azurewebsites.net/auth-end.html?clientId=08627c1d-e92e-4ab7-a41f-12c7dd5d0ff5",
			"type": "Spa"
		}
	],
	"requiredResourceAccess": [
		{
			"resourceAppId": "00000003-0000-0000-c000-000000000000",
			"resourceAccess": [
				{
					"id": "0e263e50-5827-48a4-b97c-d940288653c7",
					"type": "Scope"
				},
				{
					"id": "5f8c59db-677d-491f-a6b8-5f174b11ec1d",
					"type": "Scope"
				},
				{
					"id": "4e46008b-f24c-477d-8fff-7bb4ec7aafe0",
					"type": "Scope"
				},
				{
					"id": "e383f46e-2787-4529-855e-0e479a3ffac0",
					"type": "Scope"
				},
				{
					"id": "a65f2972-a4f8-4f5e-afd7-69ccb046d5dc",
					"type": "Scope"
				},
				{
					"id": "ba47897c-39ec-4d83-8086-ee8256fa737d",
					"type": "Scope"
				},
				{
					"id": "65e50fdc-43b7-4915-933e-e8138f11f40a",
					"type": "Scope"
				},
				{
					"id": "f45671fb-e0fe-4b4b-be20-3d3ce43f1bcb",
					"type": "Scope"
				},
				{
					"id": "2219042f-cab5-40cc-b0d2-16b1540b4c5f",
					"type": "Scope"
				},
				{
					"id": "4a06efd2-f825-4e34-813e-82a57b03d1ee",
					"type": "Scope"
				},
				{
					"id": "0f4595f7-64b1-4e13-81bc-11a249df07a9",
					"type": "Scope"
				},
				{
					"id": "a9ff19c2-f369-4a95-9a25-ba9d460efc8e",
					"type": "Scope"
				},
				{
					"id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
					"type": "Scope"
				},
				{
					"id": "b340eb25-3456-403f-be2f-af7a0d370277",
					"type": "Scope"
				}
			]
		}
	],
	"samlMetadataUrl": null,
	"signInUrl": null,
	"signInAudience": "AzureADMyOrg",
	"tags": [],
	"tokenEncryptionKeyId": null

**Comment by rvwilk** [comment] 2024-02-16 16:47
Can you give instructions for gathering console logs and network trace?

**Comment by rvwilk** [comment] 2024-02-16 16:58
I may have resolved the issue. It appears I skipped this step:

In the editor that appears, find accessTokenAcceptedVersion and update the value from null to 2

**Comment by v-asshrirao** [comment] 2024-02-19 06:28
@rvwilk, Can you please confirm if the issue is resolved after updating the value in manifest?
If its resolved can we closed this ticket?

**Closed** 2024-02-26 08:03 UTC
Labels: Needs: Author Feedback, Status: No Recent Activity
