### ISSUE TITLE
Customer needs help

### ISSUE THREAD

**Issue by jugaraka** [OfficeDev/microsoft-teams-emergency-operations-center#133] opened 2023-08-17 15:06 UTC
I have a Microsoft customer who needs Support help from the TEOC team, and this is impacting C-suite, 911, Fire dept and other hospital Executive's for case 2308070040008132 at [PPI]. Business Issue: Users at [PPI] are not able to create new incidents report using Emergency Operation Center (TEOC) and this is now directly impacting the health and safety of a hospital. Please advise.

**Comment by v-prigunasek** [comment] 2023-08-17 15:49
Hi @jugaraka , 

Can you please share us the console logs and the network trace to figure out the root cause of the error they are receiving in TEOC app? 

To get a console logs, please try to access the TEOC application in the browser version of MS Teams and open Developer tools from browser (or press Ctrl + Shift + I , this will open the console window) and **replicate the error by creating new incident** then right click on the logs to Save it as a log file.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/98514691/05eee429-a29a-45c1-8dea-32a0cde44b77)

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/98514691/9eb160cf-85ff-45b9-b2b6-6871b1407041)

To get Network trace, Open the network window and Export the log trace as HAR file.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/98514691/19c1d2d4-b307-479e-acfe-1bf372524103)

Please share us these logs and HAR files to further investigate on this issue. Thanks.

**Comment by jugaraka** [comment] 2023-08-17 16:15
Thank you for the help here. We are on call with the customer currently/Troubleshooting at this time.

Justin J. Garakanian
Incident Manager - US Public Sector
***@***.******@***.***>
Hours: M-F 7 am to 4 pm - Central
Office: +1 (469) 775-0839
***@***.***

Microsoft Services Support:
https://serviceshub.microsoft.com<https://serviceshub.microsoft.com/>
Support (24/7): +1 (800) 936-3100
Support (US NAT): +1 (800) 936-3200
Support (GCC High): +1 (877) 966-7787

**Comment by v-prigunasek** [comment] 2023-08-18 09:31
In the call with customer, the issue was identified, and it was due to the group creation setting in the tenant that is set to **NO** 
(Azure Portal --> Groups --> Settings-->General -> Users can create Microsoft 365 groups in Azure portals, API or PowerShell" )

To workaround this, asked them to follow this documentation to  [Manage who can create Microsoft 365 Groups | Microsoft Learn](https://learn.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide).

Issue was resolved after implementing the solution provided in the documentation. Hence closing this ticket.

**Closed by v-prigunasek** 2023-08-18 09:31 UTC
