### ISSUE TITLE
First time run login

### ISSUE THREAD

**Issue by danmeeder1975** [OfficeDev/microsoft-teams-emergency-operations-center#303] opened 2024-12-09 21:25 UTC
First time running the app in a new environment and when user clicks login it does not seem to do anything and no screen change. Am I just dealing with a wait awhile and re test ?

**Comment by v-ajaysahu** [comment] 2024-12-10 13:53
@danmeeder1975 , thanks for bringing this to our attention.
Could you please confirm whether your deployment was successful? Additionally, please open Microsoft Teams in a browser, then access the developer tools. Open the TEOC app in Teams to attempt to reproduce the issue. Afterward, share the Manifest file you uploaded to the Teams Admin Center, along with the network traces and console logs from the developer tools.

**Comment by danmeeder1975** [comment] 2024-12-10 21:16
Feel free to close this as it turns out it was capital letters in the Base resource name.   Just a suggestion to maybe note that in the deployment notes.

**Comment by v-ajaysahu** [comment] 2024-12-12 05:01
@danmeeder1975 ,
Thank you for confirming that the issue has been resolved. We appreciate your suggestion, but we have already included it in our deployment guide. Here is the link and screenshot for your reference.
The issue occurred because the base resource name contained capital letters. Since this matter is now resolved, I will close this request. However, please feel free to add any comments if needed.
https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#3-deploy-to-your-azure-subscription
![image](https://github.com/user-attachments/assets/912a11db-ad27-416b-97d5-4d60b4938a54)

**Closed by v-ajaysahu** 2024-12-12 05:01 UTC
Labels: Needs: Attention :wave:
