### ISSUE TITLE
Error when creating an incident: An error has occurred, please try to create your incident again

### ISSUE THREAD

**Issue by sillman96** [OfficeDev/microsoft-teams-emergency-operations-center#164] opened 2024-01-19 21:57 UTC
Good afternoon, we have just deployed the app and are testing it, but upon testing first creation of an incident, we received the following error:
![error](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/28875629/3ad976a2-2f03-4e64-b1a3-810a0a226241)

I checked to ensure that we are allowing all users to create O365 Groups (we are), and I have removed the policy of adding a suffix to the end of our O365 groups that are user-generated. We continue to receive the same error.  We would really be grateful for some help with this issue. I have attached logs below:
[teams.microsoft.com-1705700865652.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/13994925/teams.microsoft.com-1705700865652.log)

Thank you so much!

**Comment by v-asshrirao** [comment] 2024-01-22 12:52
@sillman96,
Can you please try to clear the cache and replicate the issue again. This can be an intermittent issue which might be because of the policies you have earlier.
After clearing the cache is you still face this issue, request you to kindly share console logs and network trace with us.

**Comment by sanjaymittaluk** [comment] 2024-01-22 13:01
Did it , Same on Chrome and Edge , Here is screenshot
![Screenshot 2024-01-22 125939 - Chrome](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/156114106/c8f99f25-c2e6-4675-a570-49eed57129ea)
![Screenshot 2024-01-22 130123 - EDGE](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/156114106/c717dcf4-ecd7-4981-955b-a7124bf6da25)

**Comment by sillman96** [comment] 2024-01-22 17:59
Thanks for your response.  I cleared cache on both Teams app and browser and still got same result.  Here are the network trace and the logs. Is there anything that jumps out?
[logs.zip](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14013783/logs.zip)

**Comment by v-asshrirao** [comment] 2024-01-23 14:29
@sillman96, We are able to reproduce this issue at our end. Please allow us some time to analyse the issue and we will get back to you ASAP.

**Comment by v-asshrirao** [comment] 2024-02-02 05:52
@sillman96,
Thank you for your patience on this.
We have released the hotfix for this issue. Request you to kindly sync the code by following steps mentioned in this [link](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#3-sync-latest-version)

If you are still facing the issue we suggest you to clear cache and try again.

**Comment by sillman96** [comment] 2024-02-02 20:24
That did it!  Thank you so much for your attention to this and for the fix, we greatly appreciate it!

**Comment by sillman96** [comment] 2024-02-02 20:25
Resolved

**Comment by v-asshrirao** [comment] 2024-02-05 04:13
@sillman96,
We will close this ticket now. Thank you.

**Closed by v-asshrirao** 2024-02-05 04:13 UTC
Labels: Needs: Attention :wave:
