### ISSUE TITLE
Error creating incident

### ISSUE THREAD

**Issue by ABNOTECHGuy** [OfficeDev/microsoft-teams-emergency-operations-center#174] opened 2024-02-22 03:24 UTC
Hi, 
When trying to create the first incident the following error is displayed:
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/19259945/1051caa4-3422-4bf8-8d63-2fdd4e5817e8)

Have I misconfigured something?

**Comment by v-ajaysahu** [comment] 2024-02-22 04:57
@ABNOTECHGuy , Thank you for reporting this.
Can you please share console logs and network trace which will help us troubleshoot the issue.
Also request you to share the manifest files with us.

**Comment by ABNOTECHGuy** [comment] 2024-02-23 00:55
Hi @v-ajaysahu,

I was able to see that there were other incidents with similar problem. Fix was that I had to add my test user account to the Group Administrator Azure role. 

Now I'm having a similar issue when trying to UPDATE in incident with additional users in the Secondary Incident Commander role, any other role it works fine and I'm guessing it has something to do with that role making the user a co-owner of the team.
 
It errors when saving. Does the user being added have to have the Azure Group Admin role too?, or is there another role requirement that the test user account would need to update the incident?

**Comment by v-ajaysahu** [comment] 2024-02-26 13:44
Hi @ABNOTECHGuy ,
Could you please upgrade to [latest version](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version). If you're still facing issue in creation of Incident kindly let us know with the logs.
And Only Incident Commander or Secondary Incident Commanders will be able to update the incident.
If user want access to edit incident, he must be in any of the roles.

**Comment by v-ajaysahu** [comment] 2024-02-28 08:28
@ABNOTECHGuy , can you please confirm if the issue is resolved after upgrading it to latest version?
If it is resolved, can we close this ticket?

**Comment by ABNOTECHGuy** [comment] 2024-02-29 06:04
@v-ajaysahu, not sure if upgrading to v3.0 actually fixed it as I was still having the problem immediately after doing the update. 
However, I have managed to resolve it myself. Based on the below console output it seems there is a bug when adding a user as both Role Lead and Member to the Secondary Incident Commander role:

IncidentDetails.tsx:2969  EOC-Error: UpdateIncident_AddUsersToTeam 
 {"statusCode":400,"code":"BadRequest","requestId":"862b45b5-321a-4c52-80c4-c5f909e95c48","date":"2024-02-28T19:55:19.000Z","body":"{\"code\":\"BadRequest\",\"message\":\"User Ids in the payload must be unique. Following members were present multiple times '90bfd2d5-abca-489e-bf8d-4d27d7a1acc4'\",\"innerError\":{\"date\":\"2024-02-29T05:55:19\",\"request-id\":\"862b45b5-321a-4c52-80c4-c5f909e95c48\",\"client-request-id\":\"edc4e4a3-df0d-6b2b-7225-12085a6152d4\"}}"}
 
 So by not adding the user to "Role Lead" and only to the "Member" field when adding a SIC, then it succeeds. This makes sense because you can't have someone added to a Team as both an Owner and a Member.
 
 
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/19259945/d1a11716-03f1-41d3-a45e-fb512bb7268e)

 Perhaps if this can be made clear in the documentation, or in the GUI change the role options for the Secondary IC to only show the member field, then that would prevent these errors for future users.

**Comment by v-ajaysahu** [comment] 2024-03-04 11:34
@ABNOTECHGuy , this is handled in the latest version.
Requesting you to upgrading it to latest version and try again. Kindly let us know if you're still facing issue.

**Comment by ABNOTECHGuy** [comment] 2024-03-06 03:25
Hi @v-ajaysahu,

As I mentioned, I have completed the upgrade but it did not fix the issue with Secondary Incident Commander role.

**Comment by v-ajaysahu** [comment] 2024-03-08 05:33
@ABNOTECHGuy , Thank you for reporting this.
We will address this scenario in upcoming release.

**Closed** 2024-06-24 11:40 UTC
Labels: bug
