### ISSUE TITLE
Updated - WebApp Does not login but Teams Work

### ISSUE THREAD

**Issue by sanjaymittaluk** [OfficeDev/microsoft-teams-emergency-operations-center#163] opened 2024-01-19 20:48 UTC
Hello, I have successfully deployed all the setup and configuration; however, I can open the web app via URL < it just goes round and round in a circle and does not open anything with a message saying Please Wait. 

I have managed to upload the app to Teams, where it opens, but When I click on Login, it opens the login window. I try to log in, but nothing happens,  And I go back to the Login Window.

https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/156114106/ad7d8802-55b2-4203-b9d6-30b36ba513c4

I  have tried to open this in the Web Version of Teams, but it is the same.

It appears it is unable to authenticate. I have restarted the Webapp. 

What can I do to log in and troubleshoot?

Thank you

**Comment by sanjaymittaluk** [comment] 2024-01-19 21:55
Hello, Sorry to bother you. I found the mistake in API> I used the instructions from the Browser console and found the API name was wrong, and as soon as I updated. it started to work in Teams. However, I can not make the web app work. It is still stuck at please wait and keep on going in a circle. thank you

**Comment by v-asshrirao** [comment] 2024-01-22 08:30
@sanjaymittaluk, Thank you for reporting this.
Can you please open TEOC app in web version of teams and share the console logs and network trace with us for troubleshoot the issue?

**Comment by sanjaymittaluk** [comment] 2024-01-22 12:43
![Screenshot 2024-01-22 124219](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/156114106/54035095-4ce7-4ebb-96bc-b3fbd13693c2)

URL IS -  azurewebsites.net/#/tab

**Comment by v-asshrirao** [comment] 2024-01-24 14:11
@sanjaymittaluk, Can you please confirm is you are able to create and update incident successfully in web version of teams.
And share network trace with us for further troubleshooting.

Meanwhile we will try to troubleshoot this issue from our end

**Comment by sanjaymittaluk** [comment] 2024-01-24 15:18
Yes, No problem with anything else so far. I did, however, have an issue where I could not open or edit an incident, but then I removed it from the List and created it again, and it worked.

**Comment by sanjaymittaluk** [comment] 2024-01-24 15:19
> Yes, No problem with anything else so far. I did, however, have an issue where I could not open or edit an incident, but then I removed it from the List and created it again, and it worked.

**Comment by v-asshrirao** [comment] 2024-01-24 15:32
@sanjaymittaluk, Thank you for your confirmation.
azurewebsites.net/#/tab URL will always show loader that is how it is designed.
Can you please try creating one new incident now and confirm if it is working fine for you?
In this case if everything is working fine for you we will close this issue.

**Comment by sanjaymittaluk** [comment] 2024-01-24 15:38
> v-asshrirao


An error has occurred, please try to create your incident again

**Comment by v-asshrirao** [comment] 2024-01-24 15:44
@sanjaymittaluk , Can you please share console logs and network trace with us for troubleshooting.

**Comment by v-asshrirao** [comment] 2024-01-24 15:48
@sanjaymittaluk, For troubleshooting we will need logs for below scenarios.
1. When you try to create incident and its failing.
2. When incident created successfully after few attempts but you are not able to open it or edit it.

Can you please help us with logs and network trace for both scenarios.

**Comment by sanjaymittaluk** [comment] 2024-01-24 15:53
> @sanjaymittaluk, For troubleshooting we will need logs for below scenarios.
> 
> 1. When you try to create incident and its failing.
> 2. When incident created successfully after few attempts but you are not able to open it or edit it.
> 
> Can you please help us with logs and network trace for both scenarios.

![Screenshot 2024-01-24 155205](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/156114106/e26f5a00-775a-47a5-b526-9145f2df7b9d)

**Comment by sanjaymittaluk** [comment] 2024-01-24 16:31
I am not sure what has happend but we can not create incident anymore and this is completely broken

**Comment by v-asshrirao** [comment] 2024-01-24 16:46
@sanjaymittaluk, Can you please try to create incident and copy the logs from console in text file and share with us along with network trace. Without analysing the logs we will not be able to find the root cause and help you on this issue further.

**Comment by sanjaymittaluk** [comment] 2024-01-24 16:53
> @sanjaymittaluk, Can you please try to create incident and copy the logs from console in text file and share with us along with network trace. Without analysing the logs we will not be able to find the root cause and help you on this issue further.
> 
> Request you to kindly attach logs and network trace in GitHub ticket itself because we will not be able to open logs if you share over an email.

[teams.microsoft.com-1706115136500.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14041384/teams.microsoft.com-1706115136500.txt)

**Comment by v-asshrirao** [comment] 2024-01-24 17:02
@sanjaymittaluk, Thank you for sharing the logs. We will analyse this and try to get back to you ASAP.

**Comment by sanjaymittaluk** [comment] 2024-01-24 17:11
> @sanjaymittaluk, Thank you for sharing the logs. We will analyse this and try to get back to you ASAP.

do you think , it could be because one of the app service is on free with 60 minutes limit ?

**Comment by sanjaymittaluk** [comment] 2024-01-31 11:25
Hello, do you know if we need to do anything about an issue which is not allowing us to create an incident? I saw an update that a patch has been issued. Do you know if it's automatically applied, or do we need to update it somewhere?

**Comment by v-saikirang** [comment] 2024-01-31 13:08
Hi @sanjaymittaluk,

May I know which hot fix are you referring to. The hot fix we have been waiting is not deployed yet. We will keep you posted once its deployed.
Thanks.

**Comment by sanjaymittaluk** [comment] 2024-01-31 13:34
the one where 

> Hi @sanjaymittaluk,
> 
> May I know which hot fix are you referring to. The hot fix we have been waiting is not deployed yet. We will keep you posted once its deployed. Thanks.

it is the one where we could not create a new incident

**Comment by v-saikirang** [comment] 2024-01-31 13:51
Hi @sanjaymittaluk,

Yes, the Create Incident failure is happening due to an issue with a graph call and i am referring to the hot fix for the same. This is not deployed yet. We will let you know when it's ready. Thanks for your patience on this.
Thanks.

**Comment by sanjaymittaluk** [comment] 2024-01-31 14:31
> Hi @sanjaymittaluk,
> 
> Yes, the Create Incident failure is happening due to an issue with a graph call and i am referring to the hot fix for the same. This is not deployed yet. We will let you know when it's ready. Thanks for your patience on this. Thanks.

Thank you, would it be automatic or does it require any action from us

**Comment by v-asshrirao** [comment] 2024-02-02 05:53
@sanjaymittaluk,
Thank you for your patience on this.
We have released the hotfix for this issue. Request you to kindly sync the code by following steps mentioned in this [link](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#3-sync-latest-version)

If you are still facing the issue we suggest you to clear cache and try again.

**Comment by sanjaymittaluk** [comment] 2024-02-02 10:47
> @sanjaymittaluk, Thank you for your patience on this. We have released the hotfix for this issue. Request you to kindly sync the code by following steps mentioned in this [link](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#3-sync-latest-version)
> 
> If you are still facing the issue we suggest you to clear cache and try again.

You guys are Gods.. All is good now, and I can create a new Incident.  So that you know, All I had to do was Click on Sync and wait. Permissions were already there.

**Comment by v-asshrirao** [comment] 2024-02-05 04:12
@sanjaymittaluk,Glad to hear that it worked. We will go ahead and close this ticket now.

**Closed by v-asshrirao** 2024-02-05 04:12 UTC
Labels: Needs: Attention :wave:
