### ISSUE TITLE
Unable to login to App

### ISSUE THREAD

**Issue by idavis162** [OfficeDev/microsoft-teams-emergency-operations-center#192] opened 2024-04-19 20:41 UTC
The  app has been deployed and added to the team, but when I hit the login button, a prompt that says "almost there" pops up, I then hit continue, and then nothing happens.  Any help is appreciated. Thanks. 
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/167580051/c4b9863e-8874-4d72-b83c-b8f9a1fa8fe5)

**Comment by v-ajaysahu** [comment] 2024-05-02 10:29
@idavis162 , , Thank you for reporting this.
Please open teams in browser, then open the app and share console logs and network trace which will help us troubleshoot the issue.
Also request you to share the manifest files with us.

**Comment by idavis162** [comment] 2024-05-02 14:53
[Teams Info.zip](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/15190113/Teams.Info.zip)

**Comment by v-ajaysahu** [comment] 2024-05-02 16:11
@idavis162 ,
Thank you for sharing the Logs.
As per the Shared logs you are getting SSO token error. 
Manifest file which you have shared is from Azure App Registration, we need Manifest file where you generated TEOC App zip as per this [link](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#7-create-the-teams-app-packages).
Kindly verify the Client Id and Client Secret which you have added in Apps Manifest JSON file and in App Registration either it could be mismatched, or Permission is mismatched.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/55e26a5b-4e7d-45fa-ac33-51de4b72d9ed)

**Comment by idavis162** [comment] 2024-05-02 18:19
[Manifest.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/15192430/Manifest.txt)

**Comment by v-ajaysahu** [comment] 2024-05-03 07:15
@idavis162 ,
Thanks for sharing Manifest file.
Client Id seems to be correct. Kindly confirm whether Client Secret which you've added while creating the app is correct or not. 
To do this kindly navigate to your resource group and then navigate to App Service which ends with simple Auth then click on Environment Variables there you can find Client Secret verify whether it is correct or not.
Once confirmed, kindly let us know.

**Comment by idavis162** [comment] 2024-05-07 13:19
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/167580051/00a9029c-9e41-478f-a07a-db51ced19f73)
So would I use this ID? or the client secret? And where would I input that value?

**Comment by v-ajaysahu** [comment] 2024-05-07 14:03
@idavis162 ,
Please ensure that the Client ID and Client Secret correspond with the App Registration you have created as per the below link.
https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#2-register-azure-ad-application

**Comment by idavis162** [comment] 2024-05-13 21:11
So I have the correct Client ID. Where do I need to update that to try and get it to work?

**Comment by v-ajaysahu** [comment] 2024-05-14 14:47
@idavis162 ,
If your client ID is incorrect, you should delete the Resource Group and attempt the process again with the correct client ID value.

**Comment by idavis162** [comment] 2024-05-14 20:36
Just to confirm, the base resource name and app domain is the one ending in simpleauth correct? As in reference to step 4.

**Comment by v-ajaysahu** [comment] 2024-05-15 14:18
@idavis162 ,
Yes, that is correct. That's the base resource name.

**Comment by idavis162** [comment] 2024-05-15 20:25
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/167580051/db6fbbf7-f15b-4c6a-be1c-b657d28c91ab)

Which is the right app service to use for the app domain and the base resource name? I rebuilt the app but now when trying to add it, it won't allow me to add it to the team.

**Comment by idavis162** [comment] 2024-05-15 20:57
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/167580051/0b023f31-ceca-43cf-9123-3dabcfc585a9)
This is all that pops up when trying to add the app

**Comment by v-ajaysahu** [comment] 2024-05-16 14:26
@idavis162 ,
First App service name which has the base resource name.
Instead of adding to teams Channel, can you try to open the app directly and confirm here?

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/25894ed3-d810-4eae-85e4-27fed286bb5d)

**Comment by idavis162** [comment] 2024-05-16 16:28
I have confirmed the client secret is showing the correct value under the simpleauth app service. I have also made sure the base resource name is the lbbdomeoc. But now when logging this is what the console shows


Uncaught (in promise) h.InternalError: Failed to get access token with error: Get SSO token failed with error: Error: 500011 - [2024-05-16 16:26:56Z]: AADSTS500011: The resource principal named api://lbbdomeoc.azurewebsites.net/eb8db36d-0feb-4fe0-8dd7-68aed6b2aa38/access_as_user was not found in the tenant named City of Lubbock. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: 936a398f-5a20-43c4-b7d4-4fe6dab06400 Correlation ID: d1b007e2-60f7-442e-bb70-281582811da1 Timestamp: 2024-05-16 16:26:56Z - Correlation ID: d1b007e2-60f7-442e-bb70-281582811da1 - Trace ID: 936a398f-5a20-43c4-b7d4-4fe6dab06400

**Comment by v-ajaysahu** [comment] 2024-05-17 05:44
@idavis162 ,
Please share your email address and your availability so that we can schedule a MS Teams Call to troubleshoot this issue.

**Comment by idavis162** [comment] 2024-05-17 16:24
I am free today from 1-5 CST or anytime Monday-Friday 9-5 CST
My email is ***@***.***

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by v-ajaysahu** [comment] 2024-05-20 06:01
@idavis162 ,
Please share your email address through GitHub. You've shared the email address through email which will not be visible to us.

**Comment by idavis162** [comment] 2024-05-20 13:05
idavis@mylubbock.us

**Comment by v-ajaysahu** [comment] 2024-05-20 14:22
@idavis162 ,
I have scheduled a meeting for the 21st of May at 9:30 AM CST to address the issue. 
I hope this proposed time is suitable for you.

**Comment by idavis162** [comment] 2024-05-21 18:47
Got it now. Thanks!

**Comment by v-ajaysahu** [comment] 2024-05-22 04:52
@idavis162 ,
As your issue has been resolved, I am closing this request. Please feel free to comment if you require further assistance.

**Closed by v-ajaysahu** 2024-05-22 04:52 UTC
Labels: Needs: Attention :wave:
